# Generated by Django 5.2.5 on 2025-08-24 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_transaction_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='terminal',
            name='merchant',
        ),
    ]
