# Generated by Django 5.2.5 on 2025-08-25 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_remove_terminal_merchant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='latitude',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='terminal',
            name='longitude',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
