# Generated by Django 5.2.5 on 2025-08-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0004_alter_terminal_latitude_alter_terminal_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terminal',
            name='latitude',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='terminal',
            name='longitude',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
