# Generated by Django 5.2.5 on 2025-08-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0005_alter_terminal_latitude_alter_terminal_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
    ]
