# Generated by Django 5.2.5 on 2025-08-25 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0006_mcc'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='mcc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='v1.mcc'),
        ),
    ]
